### ISSUE TITLE
json发送对的时候\n会被保留

### ISSUE THREAD

**Issue by name-jerry** [lima1909/resty.nvim#1]
如果json有换行符，在请求时会被转为\n发送出去，能在解析的时候去掉body中的空白字符串吗

**Comment by lima1909** [comment]
The parser is adapted. Does the problem still exist?
Can you give me an example of a test case @name-jerry ?

**Comment by name-jerry** [comment]
> The parser is adapted. Does the problem still exist? Can you give me an example of a test case @name-jerry ?

It's taken care of. Thank you
